# Run Fluentd as a DaemonSet
kind: DaemonSet

# Mount host logs so Fluentd can read container logs
extraVolumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: dockercontainers
    hostPath:
      path: /var/lib/docker/containers
  - name: posfiles
    hostPath:
      path: /var/log/fluentd-pos
      type: DirectoryOrCreate

extraVolumeMounts:
  - name: varlog
    mountPath: /var/log
  - name: dockercontainers
    mountPath: /var/lib/docker/containers
    readOnly: true
  - name: posfiles
    mountPath: /var/log/fluentd-pos

# Add Kafka plugin
plugins:
  - fluent-plugin-kafka

# Fluentd pipeline
config: |-
  # 1. Tail container logs
  <source>
    @type tail
    path /var/log/containers/*.log
    pos_file /var/log/fluentd-pos/containers.log.pos
    tag kubernetes.*
    format json
  </source>

  # 2. Enrich with Kubernetes metadata
  <filter kubernetes.**>
    @type kubernetes_metadata
    kubernetes_url 'https://kubernetes.default.svc:443'
    verify_ssl false
    ca_file /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file /var/run/secrets/kubernetes.io/serviceaccount/token
  </filter>

  # 3. Forward logs to Kafka
  <match kubernetes.**>
    @type kafka2
    brokers kafka.logging.svc.cluster.local:9092
    default_topic kubernetes-logs

    # Auth (SCRAM-SHA-256 with SASL_PLAINTEXT)
    sasl_over_ssl false
    username user1
    password tVnCLXgzPE
    scram_mechanism sha256

    use_event_time true

    <format>
      @type json
    </format>
  </match>

# Resource requests/limits
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
