# Run Fluentd as a DaemonSet
kind: DaemonSet

# Mount host logs so Fluentd can read container logs
extraVolumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: dockercontainers
    hostPath:
      path: /var/lib/docker/containers
  - name: posfiles
    hostPath:
      path: /var/log/fluentd-pos
      type: DirectoryOrCreate

extraVolumeMounts:
  - name: varlog
    mountPath: /var/log
  - name: dockercontainers
    mountPath: /var/lib/docker/containers
    readOnly: true
  - name: posfiles
    mountPath: /var/log/fluentd-pos

# Main Fluentd configuration (chart expects this under `config`)
config: |-
  <source>
    @type tail
    path /var/log/containers/*.log
    pos_file /var/log/fluentd-pos/containers.log.pos
    tag kubernetes.*
    format json
  </source>

  <filter kubernetes.**>
    @type kubernetes_metadata
    kubernetes_url 'https://kubernetes.default.svc:443'
    verify_ssl false
    ca_file /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file /var/run/secrets/kubernetes.io/serviceaccount/token
  </filter>

  <match **>
    @type stdout
  </match>

# Resource requests/limits
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
