apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Daniel-Makhoba-Emmanuel/GitOps-Repo.git
    path: multiple-apps-multiple-environments/apps/echo/chart
    targetRevision: 'main'
    helm:
      valueFiles:
        - ../values/dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
