apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Daniel-Makhoba-Emmanuel/Gray-Crest-Cloud-Native-Logging-and-Monitoring-System-Demo.git
    path: applications/apps/nginx/chart
    targetRevision: 'main'
    helm:
      valueFiles:
        - ../values/dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
