apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-parent
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Daniel-Makhoba-Emmanuel/GitOps-Repo.git
    path: multiple-apps-multiple-environments/argo/apps
    targetRevision: 'main'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
